<a href="https://colab.research.google.com/github/Afkar5115/Kecerdasan_Buatan_TI-1B_2025/blob/main/Jobsheet_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**# Jobsheet 2**




# Percobaan 2

In [7]:
x = min(5, 10, 25)
y = max(6, 12, 18)
print(x)
print(y)

5
18


In [8]:
x = abs(-7.25)
print(x)

7.25


In [9]:
import math
x = math.pow(4, 3)
print(x)

64.0


In [10]:
import math
x = math.sqrt(64)
print(x)

8.0


In [11]:
import math
x = math.ceil(1.4)
y = math.floor(1.4)
print(x)
print(y)


2
1


In [12]:
import math
x = math.pi
print(x)


3.141592653589793


# Percobaan 3

In [16]:
math.sin(1)

0.8414709848078965

In [17]:
math.cos(1)

0.5403023058681398

In [18]:
math.tan(1)

1.5574077246549023

In [19]:
math.log(10)


2.302585092994046

In [21]:
math.log10(10)


1.0

In [22]:
math.degrees(30)


1718.8733853924696

In [36]:
import math

p = (1, 2)
q = (4, 6)

jarak = math.dist(p, q)
print(jarak)

5.0


In [27]:
math.factorial(5)


120

In [35]:
print(math.fmod(10,4))


2.0


In [37]:
print(math.isnan(float('nan')))
print(math.isnan(10))
print(math.isnan(3.14))

True
False
False


In [31]:
math.gamma(6)


120.0

In [32]:
math.perm(7)

5040

# Percobaan 4

In [42]:
import numpy as np
A = np.array([[80, 30, 25],[50, 20, 10]])
B = np.array([[30, 60, 15],[10, 30, 30]])

hasil = A + B
print(hasil)


[[110  90  40]
 [ 60  50  40]]


In [45]:
import numpy as np
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

hasil = np.dot(A, B)
print(hasil)


2025


In [52]:
import numpy as np
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

Hasil = np.cross(A, B)
print(Hasil)


[-305 -110  350]


# Tugas Praktikum 1

In [53]:
import numpy as np


A = np.array([[3, 1],
              [2, 0]])

B = np.array([[2, 1],
              [1, -1]])

C = np.array([[-1, 1, 2],
              [2, 0, -1]])


hasil = np.dot(A, B)
HASIL = np.dot(B, C)


print("Hasil A x B:\n", hasil)
print("Hasil B x C:\n", HASIL)


Hasil A x B:
 [[7 2]
 [4 2]]
Hasil B x C:
 [[ 0  2  3]
 [-3  1  3]]


# Tugas Praktikum 2

In [55]:
import math


faktorial_6 = math.factorial(6)
faktorial_8 = math.factorial(8)
faktorial_5 = math.factorial(5)


hasil = faktorial_8 / faktorial_5

print("Hasil")
print("6! =", faktorial_6)
print("8! / 5! =", hasil)


Hasil
6! = 720
8! / 5! = 336.0


# Tugas Praktikum 3

In [58]:
import numpy as np

# Definisi vektor A dan B
A = np.array([5, 3, 7])
B = np.array([12, -3, 1])

magnitude_A = np.linalg.norm(A)
magnitude_B = np.linalg.norm(B)

dot_product = np.dot(A, B)

cross_product = np.cross(A, B)


print("Panjang vektor A =", magnitude_A)
print("Panjang vektor B =", magnitude_B)
print("Perkalian titik A . B =", dot_product)
print("Perkalian silang A x B =", cross_product)


Panjang vektor A = 9.1104335791443
Panjang vektor B = 12.409673645990857
Perkalian titik A . B = 58
Perkalian silang A x B = [ 24  79 -51]
